# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies for frontend
      run: cd frontend && npm ci

    - name: Install dependencies for backend
      run: cd server && npm ci

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Save node_modules folders
      uses: actions/upload-artifact@v2
      with:
        name: node_modules
        path: |
          frontend/node_modules
          server/node_modules

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v2

    - name: fetch node_modules
      uses: actions/download-artifact@v2
      with:
        name: node_modules

    - name: Run tests
      run: npm test --if-present

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: fetch node_modules
      uses: actions/download-artifact@v2
      with:
        name: node_modules

    - name: Build production code
      run: npm run build

    - name: Save generated production code
      uses: actions/upload-artifact@v2
      with:
        name: dist_folders
        path: |
          frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: fetch dist folders
      uses: actions/download-artifact@v2
      with:
        name: dist_folders

    - name: Deploy to github pages 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: frontend/dist
 