# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  deps:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies for frontend
      run: cd frontend && npm ci

    - name: Install dependencies for backend
      run: cd server && npm ci

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Run tests
      run: npm test --if-present

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Build production code
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to github pages 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: frontend/dist
 